---
title: Mouse.click()
---




= Mouse.click()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
Sends a momentary click to the computer at the location of the cursor. This is the same as pressing and immediately releasing the mouse button.

`Mouse.click()` defaults to the left mouse button.
[%hardbreaks]


[float]
=== Синтаксис
`Mouse.click()` +
`Mouse.click(button)`


[float]
=== Параметри
`button`: which mouse button to press. Allowed data types: `char`.

* `MOUSE_LEFT` (default)
* `MOUSE_RIGHT`
* `MOUSE_MIDDLE`


[float]
=== Повертає
Nothing

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Приклад коду
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
#include <Mouse.h>

void setup() {
  pinMode(2, INPUT);
  //initiate the Mouse library
  Mouse.begin();
}

void loop() {
  //if the button is pressed, send a left mouse click
  if (digitalRead(2) == HIGH) {
    Mouse.click();
  }
}
----
[%hardbreaks]

[float]
=== Примітки та попередження
When you use the `Mouse.click()` command, the Arduino takes over your mouse! Make sure you have control before you use the command. A pushbutton to toggle the mouse control state is effective.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Дивись також

[role="language"]
* #LANGUAGE# link:../mouseend[Mouse.end()]
* #LANGUAGE# link:../mousemove[Mouse.move()]
* #LANGUAGE# link:../mousepress[Mouse.press()]
* #LANGUAGE# link:../mouserelease[Mouse.release()]
* #LANGUAGE# link:../mouseispressed[Mouse.isPressed()]

--
// SEE ALSO SECTION ENDS
