---
title: pinMode()
categories: [ "Functions" ]
subCategories: [ "Digital I/O" ]
---


//
:ext-relative: .html

= pinMode()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
Configures the specified pin to behave either as an input or an output. See the http://arduino.cc/en/Tutorial/DigitalPins[Digital Pins] page for details on the functionality of the pins.
[%hardbreaks]
As of Arduino 1.0.1, it is possible to enable the internal pullup resistors with the mode `INPUT_PULLUP`. Additionally, the `INPUT` mode explicitly disables the internal pullups.
[%hardbreaks]


[float]
=== Синтаксис
`pinMode(pin, mode)`


[float]
=== Параметри
`pin`: the Arduino pin number to set the mode of. +
`mode`: `INPUT`, `OUTPUT`, or `INPUT_PULLUP`. See the http://arduino.cc/en/Tutorial/DigitalPins[Digital Pins] page for a more complete description of the functionality.


[float]
=== Повертає
Нічого

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Приклад коду
The code makes the digital pin 13 `OUTPUT` and Toggles it `HIGH` and `LOW`

[source,arduino]
----
void setup() {
  pinMode(13, OUTPUT);    // sets the digital pin 13 as output
}

void loop() {
  digitalWrite(13, HIGH); // sets the digital pin 13 on
  delay(1000);            // waits for a second
  digitalWrite(13, LOW);  // sets the digital pin 13 off
  delay(1000);            // waits for a second
}
----
[%hardbreaks]

[float]
=== Примітки та попередження
The analog input pins can be used as digital pins, referred to as A0, A1, etc.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Дивись також

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/DigitalPins[Description of the digital pins^]

--
// SEE ALSO SECTION ENDS
