---
title: analogWrite()
categories: [ "Functions" ]
subCategories: [ "Analog I/O" ]
---





= analogWrite()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
Виводить на контакт аналоговий сигнал (http://arduino.cc/en/Tutorial/PWM[ШІМ]). Може використовуватися для керування яскравістю світлодіода або керуванням швидкістю двигуна. Після виклику `analogWrite()`, на контакті буде генеруватись постійний прямокутний сигнал з визначеним коефіцієнтом заповнення до наступного виклику `analogWrite()` (або виклику `digitalRead()` чи `digitalWrite()`) на тому самому контакті. 
[options="header"]
|========================================================================================================
| Плата                     | Контакти ШІМ                   | Частота ШІМ
| Uno, Nano, Mini           | 3, 5, 6, 9, 10, 11             | 490 Гц (контакти 5 та 6: 980 Гц)
| Mega                      | 2 - 13, 44 - 46                | 490 Гц (контакти 4 та 13: 980 Гц)
| Leonardo, Micro, Yún      | 3, 5, 6, 9, 10, 11, 13         | 490 Гц (контакти 3 та 11: 980 Гц)
| Uno WiFi Rev2, Nano Every | 3, 5, 6, 9, 10                 | 976 Гц
| MKR boards *              | 0 - 8, 10, A3, A4              | 732 Гц
| MKR1000 WiFi *            | 0 - 8, 10, 11, A3, A4          | 732 Гц
| Zero *                    | 3 - 13, A0, A1                 | 732 Гц
| Nano 33 IoT *             | 2, 3, 5, 6, 9 - 12, A2, A3, A5 | 732 Гц
| Nano 33 BLE/BLE Sense     | 1 - 13, A0 - A7                | 500 Гц
| Due **                    | 2-13                           | 1000 Гц
| 101                       | 3, 5, 6, 9                     | контакти 3 та 9: 490 Гц, контакти 5 та 6: 980 Гц
|========================================================================================================
{empty}* На додаток до можливостей ШІМ на наведених вище контактах, плати MKR, Nano 33 IoT та Zero мають справжній аналоговий вихід при використанні `analogWrite()` на контакті `DAC0` (`A0`). +
{empty}** На додаток до можливостей ШІМ на наведених вище контактах, плати Due мають справжній аналоговий вихід при використанні `analogWrite()` на контактах `DAC0` і `DAC1`.

[%hardbreaks]

Не обов'язково викликати `pinMode()` перед викликом `analogWrite()`, щоб встановити контакт як вихідний.
Функція `analogWrite()` не має нічого спільного з аналоговими контактами або функцією `analogRead()`.
[%hardbreaks]


[float]
=== Синтаксис
`analogWrite(pin, value)`


[float]
=== Параметри
`pin`: номер або ім'я вихідного контакту. Очікує тип даних: `int`. +
`value`: коефіцієнт заповнення: від 0 (завжди вимкнено) і 255 (завжди увімкнено). Очікує тип даних: `int`.


[float]
=== Повертає
Нічого

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Приклад коду
Регулює яскравістю світлодіода пропорційно значенню, зчитаному з потенціометра.


[source,arduino]
----
int ledPin = 9;      // Світлодіод підключений до цифрового виводу 9
int analogPin = 3;   // Потенціометр підключений до аналогового виводу 3
int val = 0;         // Зчитане значення з потенціометра

void setup() {
  pinMode(ledPin, OUTPUT);  // Встановлює контакт як вихід
}

void loop() {
  val = analogRead(analogPin);  // Зчитує з вхідного контакту
  analogWrite(ledPin, val / 4); // Значення analogRead змінюються від 0 до 1023, значення analogWrite від 0 до 255
}
----
[%hardbreaks]


[float]
=== Примітки та попередження
На контактах 5 та 6 ШІМ-сигнал генерується з вищим коефіцієнтом заповнення ніж очікується. Це відбувається через взаємодією з функціями `millis()` та `delay()`, які мають один і той же внутрішній таймер, який використовується для генерації цього ШІМ сигналу. Це буде помітно здебільшого на малому коефіцієнті заповнення (наприклад, 0 - 10) і може призвести до того, що значення 0 не вимкне повністю вихід на контактах 5 і 6.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Дивись також

[role="language"]
* #LANGUAGE# link:../../zero-due-mkr-family/analogwriteresolution[analogWriteResolution()]

[role="definition"]
* #DEFINITION# http://arduino.cc/en/Tutorial/PWM[ШІМ^]

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Blink[Blink^]

--
// SEE ALSO SECTION ENDS
