---
title: analogReference()
categories: [ "Functions" ]
subCategories: [ "Analog I/O" ]
---


//


= analogReference()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
Налаштовує опорну напругу для аналогового входу (тобто значення, яке використовується як верхня межа вхідного діапазону). Варіанти:

Плати Arduino AVR (Uno, Mega, Leonardo, тощо)

* DEFAULT: аналогове значення за замовчуванням 5 вольт (на платах Arduino 5V) або 3.3 вольта (на платах Arduino 3.3V)
* INTERNAL: вбудована опорна напруга, відповідно 1.1 вольта на ATmega168 та ATmega328P та 2.56 вольта на ATmega32U4 та ATmega8 (недоступна на Arduino Mega)
* INTERNAL1V1: вбудована опорна напруга 1.1В (тільки для Arduino Mega)
* INTERNAL2V56: вбудована опорна напруга 2.56В (тільки для Arduino Mega)
* EXTERNAL: використовується напруга як опорна, що подається на контакт AREF (лише від 0 до 5В).

Плати Arduino SAMD (Zero, тощо)

* AR_DEFAULT: опорна напруга за замовченням 3.3В
* AR_INTERNAL: вбудована опорна напруга 2.23В
* AR_INTERNAL1V0: вбудована опорна напруга 1.0В
* AR_INTERNAL1V65: вбудована опорна напруга 1.65В
* AR_INTERNAL2V23: вбудована опорна напруга 2.23В
* AR_EXTERNAL: використовується напруга як опорна, що подається на контакт AREF

Плати Arduino megaAVR (Uno WiFi Rev2)

* DEFAULT: вбудована опорна напруга 0.55В
* INTERNAL: вбудована опорна напруга 0.55В
* VDD: Vdd від ATmega4809. 5В на the Uno WiFi Rev2
* INTERNAL0V55: вбудована опорна напруга 0.55В
* INTERNAL1V1: вбудована опорна напруга 1.1В
* INTERNAL1V5: вбудована опорна напруга 1.5В
* INTERNAL2V5: вбудована опорна напруга 2.5В
* INTERNAL4V3: вбудована опорна напруга 4.3В
* EXTERNAL: використовується напруга як опорна, що подається на контакт AREF (лише від 0 до 5В)

Плати Arduino SAM (Due)

* AR_DEFAULT: опорна напруга за замовченням 3.3В. Це єдиний варіант що підтримується для Due.

Плати Arduino mbed-enabled (лише Nano 33 BLE): доступно при використанні платформи _Arduino mbed-enabled Boards_, або _Arduino nRF528x Boards (Mbed OS)_ версії 1.1.6 або пізнішої

* AR_VDD: опорна напруга за замовченням 3.3В
* AR_INTERNAL: вбудована опорна напруга 0.6В
* AR_INTERNAL1V2: опорна напруга 1.2В (внутрішня опорна напруга 0.6В з коефіцієнтом посилення 2)
* AR_INTERNAL2V4: опорна напруга 2.4В (внутрішня опорна напруга 0.6В з коефіцієнтом посилення 4)

[%hardbreaks]


[float]
=== Синтаксис
`analogReference(type)`


[float]
=== Параметри
`type`: який тип опорної напруги використовувати (див. перелік варіантів в описі).


[float]
=== Повертає
Нічого

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Примітки та попередження
Після зміни аналогової опорної напруги перші кілька показань з `analogRead()` можуть бути неточними.

*Не використовуйте нічого менше 0В або більше 5В для зовнішньої опорної напруги на контакті AREF! Якщо ви використовуєте зовнішню опорну напругу на контакті AREF, перед викликом `analogRead()` необхідно встановити аналогову опорну напругу на EXTERNAL.* В іншому випадку ви замикаєте активну опорну напругу (генеровану внутрішньо) та контакт AREF, що може пошкодити мікроконтролер на платі Arduino.

Крім того, ви можете приєднати зовнішню опорну напругу до виводу AREF через резистор 5K, що дозволяє перемикатися між зовнішньою та внутрішньою опорними напругами. Зверніть увагу, що резистор змінить напругу, яка використовується як опорна, оскільки на контакті AREF є внутрішній резистор 32K. Вони діють як дільник напруги, тому, наприклад, 2,5В, подані через резистор, дадуть вихід 2.5 * 32 / (32 + 5) = ~2.2В на контакті AREF.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Дивись також

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/AnalogInputPins[Опис вхідних аналогових контактів^]

--
// SEE ALSO SECTION ENDS
