---
title: constrain()
categories: [ "Functions" ]
subCategories: [ "Math" ]
---





= constrain(x, a, b)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
Constrains a number to be within a range.
[%hardbreaks]


[float]
=== Синтаксис
`constrain(x, a, b)`


[float]
=== Параметри
`x`: the number to constrain Очікує тип даних: all data types. +
`a`: the lower end of the range. Очікує тип даних: all data types. +
`b`: the upper end of the range. Очікує тип даних: all data types.


[float]
=== Повертає
x: if x is between a and b. +
a: if x is less than a. +
b: if x is greater than b.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Приклад коду
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
The code limits the sensor values to between 10 to 150.

[source,arduino]
----
sensVal = constrain(sensVal, 10, 150);  // limits range of sensor values to between 10 and 150
----

[float]
=== Примітки та попередження
Because of the way the `constrain()` function is implemented, avoid using other functions inside the brackets, it may lead to incorrect results.

This code will yield incorrect results:
[source,arduino]
----
int constrainedInput = constrain(Serial.parseInt(), minimumValue, maximumValue);   // avoid this
----

Use this instead:
[source,arduino]
----
int input = Serial.parseInt();  // keep other operations outside the constrain function
int constrainedInput = constrain(input, minimumValue, maximumValue);
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Дивись також

--
// SEE ALSO SECTION ENDS
