---
title: pow()
categories: [ "Functions" ]
subCategories: [ "Math" ]
---





= pow(base, exponent)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
Calculates the value of a number raised to a power. `pow()` can be used to raise a number to a fractional power. This is useful for generating exponential mapping of values or curves.
[%hardbreaks]


[float]
=== Синтаксис
`pow(base, exponent)`


[float]
=== Параметри
`base`: the number. Очікує тип даних: `float`. +
`exponent`: the power to which the base is raised. Очікує тип даних: `float`.


[float]
=== Повертає
The result of the exponentiation. Тип даних: `double`.

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Приклад коду
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Calculate the value of x raised to the power of y:
[source,arduino]
----
z = pow(x, y);
----
See the (http://arduino.cc/playground/Main/Fscale[fscale]) sketch for a more complex example of the use of `pow()`.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Дивись також

[role="definition"]
* #DEFINITION# link:../../../variables/data-types/float[float]
* #DEFENITION# link:../../../variables/data-types/double[double]

--
// SEE ALSO SECTION ENDS
