---
title: "isSpace()"
categories: [ "Functions" ]
subCategories: [ "Characters" ]
---





= isSpace(thisChar)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
Аналізує, чи є аргумент порожнім символом. Повертає true, якщо є пробілом, зміною сторінки (`'\f'`), новим рядком (`'\n'`), поверненням каретки (`'\r'`), горизонтальною табуляцією (`'\t'`) або вертикальною табуляцією (`'\v'`).
[%hardbreaks]


[float]
=== Синтаксис
`isSpace(thisChar)`


[float]
=== Параметри
`thisChar`: змінна. Очікує тип даних: `char`.


[float]
=== Повертає
`true`: if thisChar is a white-space character.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Приклад коду

[source,arduino]
----
if (isSpace(myChar)) {  // Перевіряє, чи myChar є порожнім символом
  Serial.println("The character is white-space");
} else {
  Serial.println("The character is not white-space");
}
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Дивись також

[role="language"]
* #LANGUAGE#  link:../../../variables/data-types/char[char]
* #LANGUAGE#  link:../../../structure/control-structure/if[if (умовні оператори)]
* #LANGUAGE#  link:../../../structure/control-structure/while[while (умовні оператори)]
* #LANGUAGE# link:../../communication/serial/read[read()]

--
// SEE ALSO SECTION ENDS
