---
title: noInterrupts()
categories: [ "Functions" ]
subCategories: [ "Interrupts" ]
---





= noInterrupts()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
Disables interrupts (you can re-enable them with `interrupts()`). Interrupts allow certain important tasks to happen in the background and are enabled by default. Some functions will not work while interrupts are disabled, and incoming communication may be ignored. Interrupts can slightly disrupt the timing of code, however, and may be disabled for particularly critical sections of code.
[%hardbreaks]


[float]
=== Синтаксис
`noInterrupts()`


[float]
=== Параметри
None


[float]
=== Повертає
Нічого

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Приклад коду
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
The code shows how to enable interrupts.

[source,arduino]
----
void setup() {}

void loop() {
  noInterrupts();
  // critical, time-sensitive code here
  interrupts();
  // other code here
}
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Дивись також

--
// SEE ALSO SECTION ENDS
