---
title: "toFloat()"
categories: [ "Data Types" ]
subCategories: [ "StringObject Function" ]
---





= toFloat()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
Converts a valid String to a float. The input String should start with a digit. If the String contains non-digit characters, the function will stop performing the conversion. For example, the Strings "123.45", "123", and "123fish" are converted to 123.45, 123.00, and 123.00 respectively. Note that "123.456" is approximated with 123.46. Note too that floats have only 6-7 decimal digits of precision and that longer Strings might be truncated.

[%hardbreaks]


[float]
=== Синтаксис
`myString.toFloat()`


[float]
=== Параметри
`myString`: a variable of type `String`.


[float]
=== Повертає
If no valid conversion could be performed because the String doesn't start with a digit, a zero is returned. Тип даних: `float`.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Дивись також

[role="example"]
* #EXAMPLE# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String Tutorials^]
--
// SEE ALSO SECTION ENDS
