---
title: Stream.setTimeout()
---




= setTimeout()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
`setTimeout()` sets the maximum milliseconds to wait for stream data, it defaults to 1000 milliseconds. This function is part of the Stream class, and can be called by any class that inherits from it (Wire, Serial, etc). See the link:../../stream[Stream class] main page for more information.
[%hardbreaks]


[float]
=== Синтаксис
`stream.setTimeout(time)`


[float]
=== Параметри
`stream`: an instance of a class that inherits from Stream. +
`time`: timeout duration in milliseconds. Очікує тип даних: `long`.


[float]
=== Повертає
Nothing

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Примітки та попередження
Stream functions that use the timeout value set via `setTimeout()`:

* `find()`
* `findUntil()`
* `parseInt()`
* `parseFloat()`
* `readBytes()`
* `readBytesUntil()`
* `readString()`
* `readStringUntil()`

[%hardbreaks]

--
// HOW TO USE SECTION ENDS
