---
title: constants
categories: [ "Variables" ]
subCategories: [ "Constants" ]
---

= Constants


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
== Опис
Константи це попередньо визначені вирази в мові Ардуіно. 
Вони використовуютсья для того, щоб спростити читання програми. 
Ми поділяємо константи на декілька груп:
Constants are predefined expressions in the Arduino language. They are used to make the programs easier to read. We classify constants in groups:

[float]
== Визначення Логічних Станів: правда(true) і неправда(false) (Логічні Константи)
В мові Ардуіно ми використовуємо дві константи для позначення правдивого або хибного стану: `true`, або `false`.
There are two constants used to represent truth and falsity in the Arduino language: `true`, and `false`.

[float]
=== false
`false` є простішим з двох можливих станів. 
false позначається як 0 (нуль).
`false` is the easier of the two to define. false is defined as 0 (zero).
[%hardbreaks]

[float]
=== true
`true` часто позначається як 1, що є правильним, але true має дещо ширше визначення. 
Будь яке число яке не є 0 позначає правдивий стан, або true. 
Тобто -1, 2 і -200 також позначають правдивий стан в логічних виразах.
`true` is often said to be defined as 1, which is correct, but true has a wider definition. 
Any integer which is non-zero is true, in a Boolean sense. So -1, 2 and -200 are all defined as true, too, in a Boolean sense.
[%hardbreaks]

Зауваж що константи `true` і `false` написані малими літерами на відміну від `HIGH`, `LOW`, `INPUT`, і `OUTPUT`.
Note that the `true` and `false` constants are typed in lowercase unlike `HIGH`, `LOW`, `INPUT`, and `OUTPUT`.
[%hardbreaks]

[float]
== Визначення Рівня Контакту: HIGH або LOW
== Defining Pin Levels: HIGH and LOW
В випадках зчитування або запису в цифровий контакт, ми маємо лише два можливих значення в якому контакт може знаходитись/бути заданим: `HIGH` або `LOW`.
When reading or writing to a digital pin there are only two possible values a pin can take/be-set-to: `HIGH` and `LOW`.

[float]
=== Високий (HIGH)
Значення Високий(HIGH) в відношенні до контакту має різне значення в залежності від того, як налаштований контакт `INPUT` чи `OUTPUT`. 
В випадках, коли контакт налаштований як `INPUT` `link:../../../functions/digital-io/pinmode[pinMode()]`, і ми зчитуємо значення з допомогою `link:../../../functions/digital-io/digitalread[digitalRead()]`, Ардуіно (ATmega) буде відповідати `HIGH` якщо:

  - напруга більша за 3.0V присутня на контакті (5V версії)
  - напруга більша за 2.0V присутня на контакті (3.3V версії)

The meaning of `HIGH` (in reference to a pin) is somewhat different depending on whether a pin is set to an `INPUT` or `OUTPUT`. When a pin is configured as an `INPUT` with `link:../../../functions/digital-io/pinmode[pinMode()]`, and read with `link:../../../functions/digital-io/digitalread[digitalRead()]`, the Arduino (ATmega) will report `HIGH` if:

  - a voltage greater than 3.0V is present at the pin (5V boards)
  - a voltage greater than 2.0V volts is present at the pin (3.3V boards)
[%hardbreaks]

Контакт також може бути налаштованим як Вхід(INPUT) задопомогою link:../../../functions/digital-io/pinmode[`pinMode()`], і в подальшому переведений в стан HIGH задопомогою `link:../../../functions/digital-io/digitalwrite[digitalWrite()]`. 
Це включить внутрішній 20К підтягуючий резистор, який підніме вхідний контакт до `HIGH` значень за виключенням випадків коли контакт опускається до `LOW` через компоненти підключені до нього. 
Як альтернатива, те ж саме можна зробити передавши `INPUT_PULLUP` як аргумент до link:../../../functions/digital-io/pinmode[`pinMode()`] функції, детальніше про це можна почитати в секції "Встановлення стану Цифрового контакту: INPUT, INPUT_PULLUP, and OUTPUT" нижче.

A pin may also be configured as an INPUT with link:../../../functions/digital-io/pinmode[`pinMode()`], and subsequently made HIGH with `link:../../../functions/digital-io/digitalwrite[digitalWrite()]`. This will enable the internal 20K pullup resistors, which will _pull up_ the input pin to a `HIGH` reading unless it is pulled `LOW` by external circuitry. This can be done alternatively by passing `INPUT_PULLUP` as argument to the link:../../../functions/digital-io/pinmode[`pinMode()`] function, as explained in more detail in the section "Defining Digital Pins modes: INPUT, INPUT_PULLUP, and OUTPUT" further below.
[%hardbreaks]

У випадках коли контакт сконфігурований як OUTPUT(вихід) через функцію link:../../../functions/digital-io/pinmode[`pinMode()`], і його значення задане як `HIGH` задопомогою link:../../../functions/digital-io/digitalwrite[`digitalWrite()`], контакт буде:

  - 5 вольт (5V версія)
  - 3.3 вольт (3.3V версія)

When a pin is configured to OUTPUT with link:../../../functions/digital-io/pinmode[`pinMode()`], and set to `HIGH` with link:../../../functions/digital-io/digitalwrite[`digitalWrite()`], the pin is at:

  - 5 volts (5V boards)
  - 3.3 volts (3.3V boards)

В цьому стані контакт може подавати струм, тобто може бути використаним для ввімкнення світло випромінюючого діоду LED підключеного через опір до "землі".
In this state it can source current, e.g. light an LED that is connected through a series resistor to ground.
[%hardbreaks]

[float]
=== Низький (LOW)
Низький `LOW` стан, також має різне значення в залежності від того, чи контакт використовується як `INPUT` чи `OUTPUT`. 
Коли контакт сконфігурований як `INPUT` використовуючи link:../../../functions/digital-io/pinmode[`pinMode()`], і дані з нього зчитуються link:../../../functions/digital-io/digitalread[`digitalRead()`], Ардуіно (ATmega) буде повертати значення LOW якщо:

  - напруга на контакті менша 1.5V  (5V версія)
  - напруга на контакті менша 1.0V (приблизно)  (3.3V версія)

The meaning of `LOW` also has a different meaning depending on whether a pin is set to `INPUT` or `OUTPUT`. When a pin is configured as an `INPUT` with link:../../../functions/digital-io/pinmode[`pinMode()`], and read with link:../../../functions/digital-io/digitalread[`digitalRead()`], the Arduino (ATmega) will report LOW if:

  - a voltage less than 1.5V is present at the pin (5V boards)
  - a voltage less than 1.0V (Approx) is present at the pin (3.3V boards)

Коли контакт сконфігурований як `OUTPUT` задопомогою link:../../../functions/digital-io/pinmode[`pinMode()`], та його стан заданий як `LOW` використовуючи link:../../../functions/digital-io/digitalwrite[`digitalWrite()`], контакт буде мати 0 вольт (для двох 5V і 3.3V версій). 
В цьому стані контакт може проводити струм до мінусу, доприкладу засвічувати LED який є підклюеним до живлення +5 вольт (або +3.3 вольт) через опір.

When a pin is configured to `OUTPUT` with link:../../../functions/digital-io/pinmode[`pinMode()`], and set to `LOW` with link:../../../functions/digital-io/digitalwrite[`digitalWrite()`], the pin is at 0 volts (both 5V and 3.3V boards). In this state it can sink current, e.g. light an LED that is connected through a series resistor to +5 volts (or +3.3 volts).
[%hardbreaks]

[float]
== Встановлення стану Цифрового контакту: INPUT, INPUT_PULLUP, and OUTPUT
== Defining Digital Pins modes: INPUT, INPUT_PULLUP, and OUTPUT
Цифровий контакт може бути використаним як `INPUT`, `INPUT_PULLUP`, або `OUTPUT`. 
Змінити стан контакту можна за допомогою link:../../../functions/digital-io/pinmode[`pinMode()`] це змінює електричну поведінку контакту.
Digital pins can be used as `INPUT`, `INPUT_PULLUP`, or `OUTPUT`. Changing a pin with link:../../../functions/digital-io/pinmode[`pinMode()`] changes the electrical behavior of the pin.

[float]
=== Контакти налаштовані як INPUT
=== Pins Configured as INPUT
Ардуіно (ATmega) контакти налаштовані як `INPUT` використовуючи link:../../../functions/digital-io/pinmode[`pinMode()`] знаходяться в _high-impedance_ стані. 
Контакти налаштовані як `INPUT` мають надзвичайно малі вимоги до компонентів які вони обслуговують, близькі до 100 Мега Ом опору перед контактом. 
Це робить їх дуже корисними для зчитування сенсорів.
Arduino (ATmega) pins configured as `INPUT` with link:../../../functions/digital-io/pinmode[`pinMode()`] are said to be in a _high-impedance_ state. Pins configured as `INPUT` make extremely small demands on the circuit that they are sampling, equivalent to a series resistor of 100 Megohms in front of the pin. This makes them useful for reading a sensor.
[%hardbreaks]

Якщо ти маєш контакт налаштований як `INPUT`, і зчитуєш дані з перемикача, в випадку коли перемикач розімкнутий стан контакту буде "плавати"("floating"), як результат зчитані дані будуть непередбачувані. 
Для того, щоб отримати правильні дані з контакту коли він відкритий, ми повинні використати підтягуючий або понижуючий опір.
Метою цього опору є підтягування контакту до необіхного значення у випадках коли контакт не підключений. 
Зазвичай використовують 10К опір, так як його значення є достатньо малим для того, щоб контакт не "плавав" і в той самий час його значення достатньо велике, щоб не пропускати занадто багато стурму коли контакт буде підключеним. 
Більше інформації http://arduino.cc/en/Tutorial/DigitalReadSerial[Digital Read Serial^].
If you have your pin configured as an `INPUT`, and are reading a switch, when the switch is in the open state the input pin will be "floating", resulting in unpredictable results. In order to assure a proper reading when the switch is open, a pull-up or pull-down resistor must be used. The purpose of this resistor is to pull the pin to a known state when the switch is open. A 10 K ohm resistor is usually chosen, as it is a low enough value to reliably prevent a floating input, and at the same time a high enough value to not draw too much current when the switch is closed. See the http://arduino.cc/en/Tutorial/DigitalReadSerial[Digital Read Serial^] tutorial for more information.
[%hardbreaks]

Якщо використовуєтсья контактижуючий опір, вихдний контакт буде `LOW` в випадках коли перемикач на його кінці розімкнутий і `HIGH` коли перемикач замкнутий.
If a pull-down resistor is used, the input pin will be `LOW` when the switch is open and `HIGH` when the switch is closed.
[%hardbreaks]

Якщо використовуєтсья підтягуючий опір, вхідний контакт буде в стані `HIGH` коли перемикач розімкнутий та в `LOW` стані коли перемикач замкнутий.
If a pull-up resistor is used, the input pin will be `HIGH` when the switch is open and `LOW` when the switch is closed.
[%hardbreaks]

[float]
=== Контакти Налаштовані як INPUT_PULLUP
=== Pins Configured as INPUT_PULLUP
Мікроконтроллер ATmega на Андруіно має внутрішній підтягуючий опір (опір підключений до живлення) який ти можеш використати. 
Якщо ти надаєш перевагу використати його замість зовнішнього підтягуючого опору, тобі потрібно використати `INPUT_PULLUP` аргумент в link:../../../functions/digital-io/pinmode[`pinMode()`].

The ATmega microcontroller on the Arduino has internal pull-up resistors (resistors that connect to power internally) that you can access. If you prefer to use these instead of external pull-up resistors, you can use the `INPUT_PULLUP` argument in link:../../../functions/digital-io/pinmode[`pinMode()`].
[%hardbreaks]

Дивись http://arduino.cc/en/Tutorial/InputPullupSerial[Input Pullup Serial^] приклад для використання.
See the http://arduino.cc/en/Tutorial/InputPullupSerial[Input Pullup Serial^] tutorial for an example of this in use.
[%hardbreaks]

Контакти налаштовані як вхідні з допомогою `INPUT` або `INPUT_PULLUP` можуть бути зруйнованими якщо підключені до напруги нищої 0(негативної напруги) або вище додатньої межі (5V або 3V).
Pins configured as inputs with either `INPUT` or `INPUT_PULLUP` can be damaged or destroyed if they are connected to voltages below ground (negative voltages) or above the positive power rail (5V or 3V).
[%hardbreaks]

[float]
=== Контакти налаштовані як OUTPUT
=== Pins Configured as OUTPUT
Контакти налаштовані як `OUTPUT` використовуючи link:../../../functions/digital-io/pinmode[`pinMode()`] знаходяться в так званому _low-impedance_ стані. 
Це означає що вони можуть надати значну кількість струму до інших компонентів. 
ATmega контакти можуть надати струм або поглинати струм до 40 mA (milliamps). 
Це робить їх корисними для підключення LED тому що LED зазвичай використовує менше 40 mA. 
Навантаження більші за 40 mА (двигуни) потребують транзистор або інші компоненти. 


Pins configured as `OUTPUT` with link:../../../functions/digital-io/pinmode[`pinMode()`] are said to be in a _low-impedance_ state. This means that they can provide a substantial amount of current to other circuits. ATmega pins can source (provide current) or sink (absorb current) up to 40 mA (milliamps) of current to other devices/circuits. This makes them useful for powering LEDs because LEDs typically use less than 40 mA. Loads greater than 40 mA (e.g. motors) will require a transistor or other interface circuitry.
[%hardbreaks]

Контакти налаштовані як вихід можуть бути пошкодженими або зруйнованими якщо вони підключені до негативного або позитивного терміналу живлення.
Pins configured as outputs can be damaged or destroyed if they are connected to either the ground or positive power rails.
[%hardbreaks]

[float]
== Призначення вбудованого: LED_BUILTIN
== Defining built-ins: LED_BUILTIN
Більшість Ардуіно плат мають контакт підключений до вмонованого на плату LED через опір. 
Константа `LED_BUILTIN` є номером контакту до якого підключений вмонтований LED.
Більшість плат мають цей LED підключеним до вифрового контакту 13.
Most Arduino boards have a pin connected to an on-board LED in series with a resistor. The constant `LED_BUILTIN` is the number of the pin to which the on-board LED is connected. Most boards have this LED connected to digital pin 13.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

--
// HOW TO USE SECTION ENDS

// SEE ALSO  SECTION BEGINS
[#see_also]
--

[float]
=== Дивись також

[role="language"]

--
// SEE ALSO SECTION ENDS
