---
title: Serial.findUntil()
---




= Serial.findUntil()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
`Serial.findUntil()` reads data from the serial buffer until a target string of given length or terminator string is found.

The function returns true if the target string is found, false if it times out.

`Serial.findUntil()` inherits from the link:../../stream[Stream] utility class.
[%hardbreaks]


[float]
=== Синтаксис
`_Serial_.findUntil(target, terminal)`


[float]
=== Параметри
`_Serial_`: serial port object. See the list of available serial ports for each board on the link:../../serial[Serial main page]. +
`target`: the string to search for. Allowed data types: `char`. +
`terminal`: the terminal string in the search. Allowed data types: `char`.


[float]
=== Повертає
Data type: `bool`.

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Дивись також

[role="language"]
* #LANGUAGE# link:../../stream[stream] +
* #LANGUAGE# link:../../stream/streamfinduntil[stream.findUntil()]

--
// SEE ALSO SECTION ENDS
