---
title: Serial.readStringUntil()
---




= readStringUntil()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
`readStringUntil()` reads characters from the serial buffer into a String. The function terminates if it times out (see link:../settimeout[setTimeout()]).

`Serial.readStringUntil()` inherits from the link:../../stream[Stream] utility class.
[%hardbreaks]


[float]
=== Синтаксис
`_Serial_.readStringUntil(terminator)`


[float]
=== Параметри
`_Serial_`: serial port object. See the list of available serial ports for each board on the link:../../serial[Serial main page]. +
`terminator`: the character to search for. Очікує тип даних: `char`.


[float]
=== Повертає
The entire `String` read from the serial buffer, up to the terminator character

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Примітки та попередження
The terminator character is discarded from the serial buffer.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Дивись також

[role="language"]
* #LANGUAGE# link:../../serial[Serial]
* #LANGUAGE# link:../begin[begin()]
* #LANGUAGE# link:../end[end()]
* #LANGUAGE# link:../available[available()]
* #LANGUAGE# link:../read[read()]
* #LANGUAGE# link:../peek[peek()]
* #LANGUAGE# link:../flush[flush()]
* #LANGUAGE# link:../print[print()]
* #LANGUAGE# link:../println[println()]
* #LANGUAGE# link:../write[write()]
* #LANGUAGE# link:../serialevent[SerialEvent()]
* #LANGUAGE# link:../../stream/streamparsefloat[stream.parseFloat()]

--
// SEE ALSO SECTION ENDS
