---
title: serialEvent()
---




= serialEvent()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
Called when data is available. Use `Serial.read()` to capture this data.
[%hardbreaks]


[float]
=== Синтаксис

[source,arduino]
----
void serialEvent() {
  //statements
}
----
For boards with additional serial ports (see the list of available serial ports for each board on the link:../../serial[Serial main page]):
[source,arduino]
----
void serialEvent1() {
  //statements
}

void serialEvent2() {
  //statements
}

void serialEvent3() {
  //statements
}
----


[float]
=== Параметри
`statements`: any valid statements


[float]
=== Повертає
Нічого

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Примітки та попередження
`serialEvent()` doesn't work on the Leonardo, Micro, or Yún.

`serialEvent()` and `serialEvent1()` don't work on the Arduino SAMD Boards

`serialEvent()`, `serialEvent1()``serialEvent2()`, and `serialEvent3()`  don't work on the Arduino Due.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Дивись також

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/SerialEvent[Serial Event^]

[role="language"]
* #LANGUAGE# link:../begin[begin()]
* #LANGUAGE# link:../end[end()]
* #LANGUAGE# link:../available[available()]
* #LANGUAGE# link:../read[read()]
* #LANGUAGE# link:../peek[peek()]
* #LANGUAGE# link:../flush[flush()]
* #LANGUAGE# link:../print[print()]
* #LANGUAGE# link:../println[println()]
* #LANGUAGE# link:../write[write()]

--
// SEE ALSO SECTION ENDS
