---
title: Serial.setTimeout()
---




= Serial.setTimeout()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
`Serial.setTimeout()` sets the maximum milliseconds to wait for serial data. It defaults to 1000 milliseconds.

`Serial.setTimeout()` inherits from the link:../../stream[Stream] utility class.
[%hardbreaks]


[float]
=== Синтаксис
`_Serial_.setTimeout(time)`


[float]
=== Параметри
`_Serial_`: serial port object. See the list of available serial ports for each board on the link:../../serial[Serial main page]. +
`time`: timeout duration in milliseconds. Очікує тип даних: `long`.


[float]
=== Повертає
Нічого

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Примітки та попередження
Serial functions that use the timeout value set via `_Serial_.setTimeout()`:

* `_Serial_.find()`
* `_Serial_.findUntil()`
* `_Serial_.parseInt()`
* `_Serial_.parseFloat()`
* `_Serial_.readBytes()`
* `_Serial_.readBytesUntil()`
* `_Serial_.readString()`
* `_Serial_.readStringUntil()`

[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Дивись також

[role="language"]
* #LANGUAGE# link:../../stream[stream]
* #LANGUAGE# link:../../stream/streamsettimeout[stream.setTimeout()]

--
// SEE ALSO SECTION ENDS
