---
title: pulseIn()
categories: [ "Functions" ]
subCategories: [ "Advanced I/O" ]
---


= pulseIn()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
Зчитує імпульс (один з двох `HIGH` або `LOW`) на контакті. Наприклад, якщо `value` встановлено `HIGH`, `pulseIn()` очікує коли на контакті `LOW` зміниться на `HIGH`, починає відраховувати час, потім очікує коли контакт перейде в `LOW` після чого зупиняє підрахунок часу. Повертає тривалість імпульсу в мікросекундах або переривається і повертає 0, якщо протягом часу очікування не було отримано жодного повного імпульсу.

Підрахунок часу роботи функції визначається емпіричним шляхом, та ймовірно, буде показувати помилки в довших імпульсах. Працює з імпульсами довжиною від 10 мікросекунд до 3 хвилин.
[%hardbreaks]


[float]
=== Синтаксис
`pulseIn(pin, value)` +
`pulseIn(pin, value, timeout)`


[float]
=== Параметри
`pin`: номер контакту Arduino, на якому потрібно зчитати імпульс. Очікує тип даних: `int`. +
`value`: тип імпульсу для очікування: один з двох link:../../../variables/constants/constants[HIGH] або link:../../../variables/constants/constants[LOW]. Очікує тип даних: `int`. +
`timeout` (необов’язковий): кількість мікросекунд на очікування запуску імпульсу; одна секунда за замовчуванням. Очікує тип даних: `unsigned long`.


[float]
=== Повертає
Тривалість імпульсу (у мікросекундах) або 0, якщо жоден імпульс не розпочався до часу очікування. Тип даних: `unsigned long`.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Приклад коду
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Приклад виводить тривалість імпульсу на контакті 7.

[source,arduino]
----
int pin = 7;
unsigned long duration;

void setup() {
  Serial.begin(9600);
  pinMode(pin, INPUT);
}

void loop() {
  duration = pulseIn(pin, HIGH);
  Serial.println(duration);
}
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Дивись також

--
// SEE ALSO SECTION ENDS
