---
title: shiftIn()
categories: [ "Functions" ]
subCategories: [ "Advanced I/O" ]
---





= shiftIn()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
Зчитує байт даних виконуючи побітовий зсув по одному біту. Починає з самого старшого (тобто крайнього лівого) або найменшого (правого) біта. Для зчитування кожного біта на тактовий контакт подається `HIGH`, далі з контакту даних зчитується біт, після чого на тактовий контакт подається `LOW`.

Для взаємодії з пристроєм який тактується по передньому фронту сигналів переконайтесь, що тактовий контакт встановлений в `LOW` перед першим викликом `shiftIn()`, наприклад викличте `digitalWrite(clockPin, LOW)`.

Ця функція є програмною реалізацією SPI; також існує link:https://www.arduino.cc/en/Reference/SPI[бібліотека SPI], що використовує апаратну реалізацію, яка є швидшою, але працює лише на певних контактах.
[%hardbreaks]


[float]
=== Синтаксис
`byte incoming = shiftIn(dataPin, clockPin, bitOrder)`


[float]
=== Параметри
`dataPin`: контакт з якого буде зчитуватись кожен біт. Очікує тип даних: `int`. +
`clockPin`: контакт тактового сигналу, який буде перемикатись для зчитування кожного біту з *dataPin*. +
`bitOrder`: задає порядок в якому будуть зсуватись біти при зчитуванні; може бути *MSBFIRST*, або *LSBFIRST*. (Most Significant Bit First Старший значний біт першим, або Least Significant Bit First Менший значний біт першим).


[float]
=== Повертає
Зчитане значення. Тип даних: `byte`.

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Дивись також

--
// SEE ALSO SECTION ENDS
