---
title: tone()
categories: [ "Functions" ]
subCategories: [ "Advanced I/O" ]
---





= tone()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
Генерує прямокутну хвилю заданої частоти (з коефіцієнтом заповнення 50%) на контакті. Можна вказати тривалість, інакше хвиля триває до виклику link:../notone[noTone()]. Контакт можна під'єднати до п’єзозуммера чи іншої колонки для відтворення звуку.

Одночасно може генеруватися лише один тон. Якщо тон вже відтворюється на іншому контакті, то виклик `tone()` не матиме ефекту. Якщо тон звучить на тому самому контакті, то виклик встановить вказану частоту.

Використання функції `tone()` заважати виходам ШІМ на контактах 3 та 11 (на всіх платах, крім Mega).

Неможливо генерувати тон нижче 31Гц. Технічні подробиці дивись у https://github.com/bhagman/Tone#ugly-details[примітках Бретта Хагмена].
[%hardbreaks]


[float]
=== Синтаксис
`tone(pin, frequency)` +
`tone(pin, frequency, duration)`


[float]
=== Параметри
`pin`: контакт Arduino, на якому генерується тон. +
`frequency`: частота тону в герцах. Очікує тип даних: `unsigned int`. +
`duration` (необов’язковий): тривалість тону в мілісекундах. Очікує тип даних: `unsigned long`.


[float]
=== Повертає
Нічого

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Примітки та попередження
Якщо ви хочете відтворити різні тони на декількох контактах, то потрібно викликати `noTone()` на одному піні, перш ніж викликати `tone()` на наступному піні.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Дивись також

[role="language"]
* #LANGUAGE# link:../../analog-io/analogwrite[analogWrite()]

[role="example"]

* #EXAMPLE# https://www.arduino.cc/en/Tutorial/BuiltInExamples/toneMelody[Tone Melody^]
* #EXAMPLE# https://www.arduino.cc/en/Tutorial/tonePitchFollower[Pitch Follower^]
* #EXAMPLE# https://www.arduino.cc/en/Tutorial/BuiltInExamples/toneKeyboard[Tone Keyboard^]
* #EXAMPLE# https://www.arduino.cc/en/Tutorial/BuiltInExamples/toneMultiple[Tone Multiple^]
* #EXAMPLE# https://www.arduino.cc/en/Tutorial/PWM[PWM^]

--
// SEE ALSO SECTION ENDS
